<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sumber Dana</name>
   <tag></tag>
   <elementGuidId>05d1b3a7-7f82-4cfb-88a4-155fa05cce21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[18]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>723e22a7-3623-4cf0-b176-7d71a3fc45f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf9d3a19-13ef-4fa7-a95b-b836de47c540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full absolute inset-0 outline-none focus:ring-0 appearance-none box-border border-0 text-base font-sans bg-white rounded pl-11 rtl:pl-0 rtl:pr-3.5 font-primary</value>
      <webElementGuid>a1c2437f-1136-4da3-a3d5-771630580b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>b96f1d27-6260-485b-b875-4118bd9afbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>multiselect-options</value>
      <webElementGuid>ff1dae30-bf27-45e9-a4fd-361b50c1f838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>Pilih Sumber Tabungan</value>
      <webElementGuid>89a08fd1-4791-4939-a958-b87f0760a500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f71efb46-ab7d-4f0c-a82b-a75c18eff82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ab2f49a-c5aa-48e6-8734-d6402bb90de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>bc705e1d-dd94-435d-a930-a0b51213571f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;grid grid-cols-6&quot;]/div[@class=&quot;col-span-6 lg:col-span-4&quot;]/div[@class=&quot;pt-[50px] pb-[30px] lg:overflow-y-auto lg:h-screen&quot;]/div[@class=&quot;container max-w-3xl mx-auto&quot;]/div[2]/div[2]/div[@class=&quot;mt-5&quot;]/form[1]/div[@class=&quot;grid grid-cols-1 lg:grid-cols-2 mt-5 gap-[30px]&quot;]/div[2]/div[@class=&quot;mb-5&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;relative mx-auto w-full flex items-center justify-end box-border cursor-pointer border border-gray-500 rounded bg-white text-base leading-snug outline-none min-h-[50px]&quot;]/input[@class=&quot;w-full absolute inset-0 outline-none focus:ring-0 appearance-none box-border border-0 text-base font-sans bg-white rounded pl-11 rtl:pl-0 rtl:pr-3.5 font-primary&quot;]</value>
      <webElementGuid>0fcfdd60-8d07-4d17-b4d2-d3cfdd748e0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[18]</value>
      <webElementGuid>230a5787-27fe-44a9-b672-72e2a267caea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div[2]/div[2]/div/form/div/div[2]/div/div/div/input</value>
      <webElementGuid>ce4c944a-2f1d-4c92-88e6-c9e0b5711a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/form/div/div[2]/div/div/div/input</value>
      <webElementGuid>d1a4454c-1476-4b44-adef-0845cf2b5c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>2674ff23-e729-4086-adcc-2955b65997f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
