<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_BANK BCA</name>
   <tag></tag>
   <elementGuidId>a80d55c0-4701-4251-a2bd-df8b6163e494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#multiselect-option-310</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='multiselect-option-310']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>64303908-931d-4387-87b3-53d10472d23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-start box-border text-left cursor-pointer text-base leading-snug py-1 px-3 text-gray-800 bg-gray-100</value>
      <webElementGuid>c3904605-1a7c-4113-adb5-4cf75f5108e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multiselect-option-310</value>
      <webElementGuid>8ca2c55b-345a-452e-aae3-445cb0468676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>67268ef4-97a8-48bd-9b96-e1d1b8b82a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>BANK BCA</value>
      <webElementGuid>496a96b0-c376-4eb5-b620-af72b419eb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bbb5cf2a-a71c-44ce-98ce-1ea382655332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pointed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>91c16eac-a2c5-41fe-8edd-7e4bb8e201b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BANK BCA</value>
      <webElementGuid>ab06fb56-6ef0-4861-a8b2-ad3d7ba46a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiselect-option-310&quot;)</value>
      <webElementGuid>9fbbb122-f505-4a22-96b8-22df4e4d35c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='multiselect-option-310']</value>
      <webElementGuid>c1e0da45-fba2-4322-a619-b8cdb3bd4ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='multiselect-options']/li)[59]</value>
      <webElementGuid>257dcdb8-4a16-4bd3-b9aa-a679fe04b622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Bank*'])[1]/following::li[1]</value>
      <webElementGuid>c798c041-3ccc-4dbc-9f3e-eaef8846ada6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Rekening*'])[1]/following::li[1]</value>
      <webElementGuid>a9afbf7a-da0f-4883-88ed-a0a16562863f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BANK BCA']/parent::*</value>
      <webElementGuid>7c3b5c82-eca5-4439-9a7b-2b9db8fb3136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/ul/li</value>
      <webElementGuid>0a4c4500-be3d-4b13-b8ca-d9f89a645762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'multiselect-option-310' and (text() = 'BANK BCA' or . = 'BANK BCA')]</value>
      <webElementGuid>510a1941-d001-4b5d-a7ec-86966eca011e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
