<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Kota Jakarta Timur</name>
   <tag></tag>
   <elementGuidId>a8c6fac1-3b08-40ea-ae09-e637b928ab75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#multiselect-option-154</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='multiselect-option-154']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b05bf920-c9d2-4da3-8cda-82a5d11ffaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-start box-border text-left cursor-pointer text-base leading-snug py-1 px-3 text-gray-800 bg-gray-100</value>
      <webElementGuid>0345b315-7670-456a-94a0-caca9d1bb951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multiselect-option-154</value>
      <webElementGuid>8ff960f3-fd4e-4565-9395-6380a8adbae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d85f9cec-f05c-4433-a780-1e70281f5135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Kota Jakarta Timur</value>
      <webElementGuid>da168991-e590-4dfb-927d-4d92fb2b70de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>69ec0ab8-1304-4072-8f8f-ce25afd90790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pointed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b7eb3c8e-7191-4c76-9638-181809c68c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kota Jakarta Timur</value>
      <webElementGuid>49301c68-b88f-4a50-9459-b022e2a24646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiselect-option-154&quot;)</value>
      <webElementGuid>12e275a1-631f-4ef6-b10d-0a9b73c3c339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='multiselect-option-154']</value>
      <webElementGuid>3a83bce5-e348-4654-bc70-806773422b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='multiselect-options']/li[5])[2]</value>
      <webElementGuid>76e1389c-5d3e-4437-9fa6-a0945ae9e00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Domisili*'])[1]/preceding::li[2]</value>
      <webElementGuid>be54cf2b-d969-470a-969c-251c7c764f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kota Jakarta Timur']/parent::*</value>
      <webElementGuid>1a245c86-e30c-49a9-af6f-6c42c0cb11ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div[2]/ul/li[5]</value>
      <webElementGuid>addd97aa-b45b-456d-a1e5-078dc7261088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'multiselect-option-154' and (text() = 'Kota Jakarta Timur' or . = 'Kota Jakarta Timur')]</value>
      <webElementGuid>5b95ead8-2dd7-4b60-90b7-2a9e3d4b206a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
