<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Mobil</name>
   <tag></tag>
   <elementGuidId>52734794-57a3-49d1-8b19-9aba5243d661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#multiselect-option-car</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='multiselect-option-car']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e304ea73-2733-44ef-a4e2-70c879a33f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-start box-border text-left cursor-pointer text-base leading-snug py-1 px-3 text-gray-800 bg-gray-100</value>
      <webElementGuid>abd5c936-18c0-4b4e-a7cf-8fb930f83465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multiselect-option-car</value>
      <webElementGuid>83486a49-9b74-43a9-8f69-1d838496f297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d718c17-472a-40b2-a953-cac48f6e797e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Mobil</value>
      <webElementGuid>a074266c-60eb-4586-bd2b-8a3379144f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f6677f4a-92fa-44ea-bd1d-25516f0c085a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pointed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>290e4d6d-0c9d-4ba9-92a0-31c0dcaf738d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobil</value>
      <webElementGuid>5e826f6b-7763-4339-be33-7d2d53d80341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiselect-option-car&quot;)</value>
      <webElementGuid>400586a8-a06b-4c7b-9bce-c5fc6708b081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='multiselect-option-car']</value>
      <webElementGuid>a2c9221a-85b1-408b-b18f-58b73c97d9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='multiselect-options']/li)[49]</value>
      <webElementGuid>b4fb10ce-b8ee-448f-8a7c-7801fe6d1eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kendaraan*'])[1]/following::li[1]</value>
      <webElementGuid>757bc588-ea89-4cdc-bc5b-42eda17ab582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor NPWP'])[1]/following::li[1]</value>
      <webElementGuid>537298a9-7b28-4ef8-aab0-77b114e0a96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobil']/parent::*</value>
      <webElementGuid>0a24f0a9-97ee-4a9b-b8dc-4ddb867200d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/ul/li</value>
      <webElementGuid>37df54f8-cec5-4beb-9525-30a7b5883345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'multiselect-option-car' and (text() = 'Mobil' or . = 'Mobil')]</value>
      <webElementGuid>e129f06a-0906-47f8-bc02-7bc476a36bea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
