<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Pribadi</name>
   <tag></tag>
   <elementGuidId>f6444ffd-a08f-49dd-a43e-18db29cbe4ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#multiselect-option-PRIBADI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='multiselect-option-PRIBADI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>667be8e7-9421-4839-b255-3a564c4e273e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-start box-border text-left cursor-pointer text-base leading-snug py-1 px-3 text-gray-800 bg-gray-100</value>
      <webElementGuid>fcfa6cff-3df7-4fbd-a7ee-0ab2d311467c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multiselect-option-PRIBADI</value>
      <webElementGuid>09fd3d27-1231-4dad-99e9-fa95c55de769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>766bbf11-7a80-4804-ac70-ef25a8a5686f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Pribadi</value>
      <webElementGuid>7aba11c8-da6f-4402-9c54-a7de83fb4a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>24233b1d-b6fc-466e-a8ed-66a8499b18e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pointed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32482aa3-3465-4fe0-8397-27356e97df51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pribadi</value>
      <webElementGuid>0ce510d6-4cce-4684-93e6-6fbd1621b226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiselect-option-PRIBADI&quot;)</value>
      <webElementGuid>75cb5944-fa82-4076-bb3f-6da98a0c373d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='multiselect-option-PRIBADI']</value>
      <webElementGuid>35e97829-2850-4195-87c4-c02181f1f090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='multiselect-options']/li)[55]</value>
      <webElementGuid>ab612eab-b149-47f1-b5e1-bbb917dcbd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tujuan Pembelian*'])[1]/following::li[1]</value>
      <webElementGuid>d66d2b8a-ae58-4928-a515-334c8c36a107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pribadi']/parent::*</value>
      <webElementGuid>ef606271-8cc6-4c85-acd3-db6336ba8cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/ul/li</value>
      <webElementGuid>b9713183-5ee9-42f6-8bcc-db00274de6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'multiselect-option-PRIBADI' and (text() = 'Pribadi' or . = 'Pribadi')]</value>
      <webElementGuid>a31d3ce8-ba48-44e8-ada3-887f8f7e96fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
