<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat Perusahaan</name>
   <tag></tag>
   <elementGuidId>2bb12797-6968-45f0-b376-a3bc59590146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div/div[2]/div/form/div/div[2]/div[3]/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cf3a61cb-8779-4939-a493-8bb4a2c43002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full focus:outline-none leading-5 border border-primary-grey bg-primary-gray rounded p-3 focus:ring-1 focus:ring-primary disabled:cursor-not-allowed disabled:opacity-50 disabled:bg-gray-300 placeholder:text-gray-400 border-primary-grey min-h-[148px]</value>
      <webElementGuid>d7f04bbb-a389-4509-988e-3402a6595ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;grid grid-cols-6&quot;]/div[@class=&quot;col-span-6 lg:col-span-4&quot;]/div[@class=&quot;pt-[50px] pb-[30px] lg:overflow-y-auto lg:h-screen&quot;]/div[@class=&quot;container max-w-3xl mx-auto&quot;]/div[2]/div[1]/form[1]/div[@class=&quot;grid grid-cols-1 lg:grid-cols-2 mt-5 gap-[30px]&quot;]/div[2]/div[@class=&quot;mb-5 min-h-[148px]&quot;]/div[@class=&quot;relative&quot;]/textarea[@class=&quot;block w-full focus:outline-none leading-5 border border-primary-grey bg-primary-gray rounded p-3 focus:ring-1 focus:ring-primary disabled:cursor-not-allowed disabled:opacity-50 disabled:bg-gray-300 placeholder:text-gray-400 border-primary-grey min-h-[148px]&quot;]</value>
      <webElementGuid>a1ef792a-fbf5-43d0-aeed-38ecb75ef98e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div[2]/div/form/div/div[2]/div[3]/div/textarea</value>
      <webElementGuid>7b63534b-d314-4f35-8b78-45f8dbe714c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Perusahaan'])[1]/following::textarea[1]</value>
      <webElementGuid>d65650f7-e77c-443e-9ce5-389ea339b275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Perusahaan'])[1]/following::textarea[1]</value>
      <webElementGuid>16644f7b-f6bd-4e20-9331-4506ecd10811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon Perusahaan'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a0c5e148-1f7e-4b2b-a4b5-e2a74707a59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPWP*'])[1]/preceding::textarea[1]</value>
      <webElementGuid>bf76737f-e8c2-411f-8f4a-d4ac616f833c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/textarea</value>
      <webElementGuid>c2c89cdd-0fba-4100-b255-c45ff159c157</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
